apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
