version: '3'
services:
   app:
     image: brahimhamdi/wiki_app:1.0
     build: ./app
     deploy:
       replicas: 3
       resources:
         limits:
           cpus: '0.01'
           memory: 500M
         reservations:
           cpus: '0.001'
           memory: 200M
     ports:
       - "8000:80"
     volumes:
       - nginx-vol1:/usr/share/nginx/wiki
       - nginx-vol2:/var/log/nginx

   db:
     image: brahimhamdi/wiki_db:1.0
     build: ./db
     ports:
       - "33066:3306"     

volumes:
        nginx-vol1:
        nginx-vol2:
