version: '3.3'
services:
   app:
     image: wiki_app:1.0
     build: ./app
     hostname: wiki_web
     container_name: wiki_web
     ports:
       - "8000:80"
     networks:
        wiki-net:
           ipv4_address: 10.10.10.2

   db:
     image: wiki_db:1.0
     build: ./db
     hostname: wiki_db
     container_name: wiki_db
     ports:
       - "33066:3306"     
     networks:
        wiki-net:
           ipv4_address: 10.10.10.3

   prometheus:
     image: prom/prometheus:latest
     hostname: prometheus
     container_name: prometheus
     restart: always
     ports:
       - 9090:9090
     volumes:
       - ./prometheus/conf:/etc/prometheus
     networks:
        wiki-net:
           ipv4_address: 10.10.10.4

   grafana:
     image: grafana/grafana
     hostname: grafana
     container_name: grafana
     ports:
       - 3000:3000
     networks:
        wiki-net:
           ipv4_address: 10.10.10.5

networks:
        wiki-net:
          ipam:
            config:
              - subnet: 10.10.10.0/28
