- name: Test handler
  hosts: all
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present
      notify:
        Start nginx
  handlers:
    - name: Start nginx
      service:
        name: nginx
        state: started
